---
config:
  theme: mc
  look: classic
  layout: elk
---
flowchart LR
    A["Metodologia de aprimoramento de processamentos de imagem"] --> B["Métricas"] & D["Construção de redes neurais"] & F["Análise de influência"] & G["Metodologia de aprimoramento"]
    B --> B2["Tempo de processamento"] & n1["Métricas de eficácia de modelos de IA (acurácia, precisão, recall, f1-score)"]
    D --> D1["Redes convolucionais"] & n2["Redes perceptron"]
    F --> F1["Dataset"] & n3["Modelo"]
    G --> G1["Combinação de abordagens unitárias"] & n4["Ajuste automático de parâmetros"]
