name: Pull Request Notification

on:
  pull_request:
    types: [opened]

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Nova versão da dissertação'
        body: |
          Uma nova versão da dissertação está pendente de aprovação. Você pode visualizá-la através do link: ${{ github.event.pull_request.html_url }}
        to: luan.w.silveira@gmail.com
        from: 'luanws-no-reply'
